# =============================================================================
#  03_build_dashboard_data.R
#  Exports the star schema as a compact data.js file that the static
#  index.html dashboard loads (works on file:// and on GitHub Pages).
# =============================================================================

suppressMessages({ library(dplyr); library(jsonlite); library(readr) })

dir.create("docs", showWarnings = FALSE)

fact  <- read_csv("data/fact_health_long.csv", show_col_types = FALSE)
dimc  <- read_csv("data/dim_country.csv",       show_col_types = FALSE)
dimi  <- read_csv("data/dim_indicator.csv",     show_col_types = FALSE)

# Nested structure for fast lookup in JS:  DATA[code][iso3][year] = value
nested <- list()
for (code in unique(fact$indicator_code)) {
  sub <- fact %>% filter(indicator_code == code)
  by_country <- list()
  for (cty in unique(sub$iso3)) {
    s2 <- sub %>% filter(iso3 == cty)
    by_country[[cty]] <- setNames(as.list(round(s2$value, 2)), as.character(s2$year))
  }
  nested[[code]] <- by_country
}

indicators <- dimi %>%
  transmute(code = indicator_code, name = indicator_name, unit, category,
            higher_is_better)

countries <- dimc %>%
  transmute(iso3, name = country_name, subregion, is_ghana, is_west_africa)

js <- paste0(
  "// Auto-generated by 03_build_dashboard_data.R - do not edit by hand.\n",
  "const DATA = ",       toJSON(nested,     auto_unbox = TRUE), ";\n",
  "const INDICATORS = ", toJSON(indicators, auto_unbox = TRUE, dataframe = "rows"), ";\n",
  "const COUNTRIES = ",  toJSON(countries,  auto_unbox = TRUE, dataframe = "rows"), ";\n"
)
writeLines(js, "docs/data.js")

cat("Wrote docs/data.js  (",
    round(file.info("docs/data.js")$size / 1024, 1), "KB )\n", sep = "")
